BEGIN TRANSACTION;
CREATE TABLE [pmp_profiletypes] (
[pftProfileTypeID] INTEGER  NOT NULL PRIMARY KEY AUTOINCREMENT,
[pftProfileType] TEXT  NULL
);
INSERT INTO "pmp_profiletypes" VALUES(1,'Individual');
INSERT INTO "pmp_profiletypes" VALUES(2,'Family');
INSERT INTO "pmp_profiletypes" VALUES(3,'Business');
DELETE FROM sqlite_sequence;
INSERT INTO "sqlite_sequence" VALUES('pmp_profiletypes',3);
INSERT INTO "sqlite_sequence" VALUES('pmp_languages',1);
INSERT INTO "sqlite_sequence" VALUES('pmp_ctypes',14);
INSERT INTO "sqlite_sequence" VALUES('pmp_contacts',4);
INSERT INTO "sqlite_sequence" VALUES('pmp_addresstypes',4);
INSERT INTO "sqlite_sequence" VALUES('pmp_categorylink',2);
INSERT INTO "sqlite_sequence" VALUES('pmp_categories',2);
INSERT INTO "sqlite_sequence" VALUES('pmp_people',2);
CREATE TABLE [pmp_languages] (
[lngLanguageID] INTEGER  NOT NULL PRIMARY KEY AUTOINCREMENT,
[lngLanguageName] TEXT  NULL,
[lngLanguageNamei18] TEXT  NULL,
[lngLanguageActive] BOOLEAN DEFAULT 'FALSE' NULL
);
INSERT INTO "pmp_languages" VALUES(1,'English','English','true');
CREATE TABLE [pmp_ctypes] (
[typContactTypeID] INTEGER  NOT NULL PRIMARY KEY AUTOINCREMENT,
[typContactType] TEXT  NULL
);
INSERT INTO "pmp_ctypes" VALUES(1,'Home Phone');
INSERT INTO "pmp_ctypes" VALUES(2,'Work Phone');
INSERT INTO "pmp_ctypes" VALUES(3,'Cell Phone');
INSERT INTO "pmp_ctypes" VALUES(4,'ICQ');
INSERT INTO "pmp_ctypes" VALUES(5,'AIM');
INSERT INTO "pmp_ctypes" VALUES(6,'MSN');
INSERT INTO "pmp_ctypes" VALUES(7,'YIM');
INSERT INTO "pmp_ctypes" VALUES(8,'Primary Email');
INSERT INTO "pmp_ctypes" VALUES(9,'Extra Email');
INSERT INTO "pmp_ctypes" VALUES(10,'Fax');
INSERT INTO "pmp_ctypes" VALUES(11,'URL');
INSERT INTO "pmp_ctypes" VALUES(12,'Perm Phone');
INSERT INTO "pmp_ctypes" VALUES(13,'Pager');
INSERT INTO "pmp_ctypes" VALUES(14,'Skype');
CREATE TABLE [pmp_countries] (
[ctyCountryID] INTEGER  NOT NULL PRIMARY KEY,
[ctyCountryCode] TEXT  NULL,
[ctyCountryName] TEXT  NULL
);
INSERT INTO "pmp_countries" VALUES(1,'AF','Afghanistan');
INSERT INTO "pmp_countries" VALUES(2,'AL','Albania');
INSERT INTO "pmp_countries" VALUES(3,'DZ','Algeria');
INSERT INTO "pmp_countries" VALUES(4,'AS','American Samoa');
INSERT INTO "pmp_countries" VALUES(5,'AD','Andorra');
INSERT INTO "pmp_countries" VALUES(6,'AO','Angola');
INSERT INTO "pmp_countries" VALUES(7,'AI','Anguilla');
INSERT INTO "pmp_countries" VALUES(8,'AQ','Antarctica');
INSERT INTO "pmp_countries" VALUES(9,'AG','Antigua And Barbuda');
INSERT INTO "pmp_countries" VALUES(10,'AR','Argentina');
INSERT INTO "pmp_countries" VALUES(11,'AM','Armenia');
INSERT INTO "pmp_countries" VALUES(12,'AW','Aruba');
INSERT INTO "pmp_countries" VALUES(13,'AU','Australia');
INSERT INTO "pmp_countries" VALUES(14,'AT','Austria');
INSERT INTO "pmp_countries" VALUES(15,'AZ','Azerbaijan');
INSERT INTO "pmp_countries" VALUES(16,'BS','Bahamas, The');
INSERT INTO "pmp_countries" VALUES(17,'BH','Bahrain');
INSERT INTO "pmp_countries" VALUES(18,'BD','Bangladesh');
INSERT INTO "pmp_countries" VALUES(19,'BB','Barbados');
INSERT INTO "pmp_countries" VALUES(20,'BY','Belarus');
INSERT INTO "pmp_countries" VALUES(21,'BE','Belgium');
INSERT INTO "pmp_countries" VALUES(22,'BZ','Belize');
INSERT INTO "pmp_countries" VALUES(23,'BJ','Benin');
INSERT INTO "pmp_countries" VALUES(24,'BM','Bermuda');
INSERT INTO "pmp_countries" VALUES(25,'BT','Bhutan');
INSERT INTO "pmp_countries" VALUES(26,'BO','Bolivia');
INSERT INTO "pmp_countries" VALUES(27,'BA','Bosnia and Herzegovina');
INSERT INTO "pmp_countries" VALUES(28,'BW','Botswana');
INSERT INTO "pmp_countries" VALUES(29,'BV','Bouvet Island');
INSERT INTO "pmp_countries" VALUES(30,'BR','Brazil');
INSERT INTO "pmp_countries" VALUES(31,'IO','British Indian Ocean Territory');
INSERT INTO "pmp_countries" VALUES(32,'BN','Brunei');
INSERT INTO "pmp_countries" VALUES(33,'BG','Bulgaria');
INSERT INTO "pmp_countries" VALUES(34,'BF','Burkina Faso');
INSERT INTO "pmp_countries" VALUES(35,'BI','Burundi');
INSERT INTO "pmp_countries" VALUES(36,'KH','Cambodia');
INSERT INTO "pmp_countries" VALUES(37,'CM','Cameroon');
INSERT INTO "pmp_countries" VALUES(38,'CA','Canada');
INSERT INTO "pmp_countries" VALUES(39,'CV','Cape Verde');
INSERT INTO "pmp_countries" VALUES(40,'KY','Cayman Islands');
INSERT INTO "pmp_countries" VALUES(41,'CF','Central African Republic');
INSERT INTO "pmp_countries" VALUES(42,'TD','Chad');
INSERT INTO "pmp_countries" VALUES(43,'CL','Chile');
INSERT INTO "pmp_countries" VALUES(44,'CN','China');
INSERT INTO "pmp_countries" VALUES(45,'CX','Christmas Island');
INSERT INTO "pmp_countries" VALUES(46,'CC','Cocos (Keeling) Islands');
INSERT INTO "pmp_countries" VALUES(47,'CO','Colombia');
INSERT INTO "pmp_countries" VALUES(48,'KM','Comoros');
INSERT INTO "pmp_countries" VALUES(49,'CG','Congo');
INSERT INTO "pmp_countries" VALUES(50,'CD','Congo, Democractic Republic of the');
INSERT INTO "pmp_countries" VALUES(51,'CK','Cook Islands');
INSERT INTO "pmp_countries" VALUES(52,'CR','Costa Rica');
INSERT INTO "pmp_countries" VALUES(53,'CI','Cote D''Ivoire (Ivory Coast)');
INSERT INTO "pmp_countries" VALUES(54,'HR','Croatia (Hrvatska)');
INSERT INTO "pmp_countries" VALUES(55,'CU','Cuba');
INSERT INTO "pmp_countries" VALUES(56,'CY','Cyprus');
INSERT INTO "pmp_countries" VALUES(57,'CZ','Czech Republic');
INSERT INTO "pmp_countries" VALUES(58,'DK','Denmark');
INSERT INTO "pmp_countries" VALUES(59,'DJ','Djibouti');
INSERT INTO "pmp_countries" VALUES(60,'DM','Dominica');
INSERT INTO "pmp_countries" VALUES(61,'DO','Dominican Republic');
INSERT INTO "pmp_countries" VALUES(62,'TP','East Timor');
INSERT INTO "pmp_countries" VALUES(63,'EC','Ecuador');
INSERT INTO "pmp_countries" VALUES(64,'EG','Egypt');
INSERT INTO "pmp_countries" VALUES(65,'SV','El Salvador');
INSERT INTO "pmp_countries" VALUES(66,'GQ','Equatorial Guinea');
INSERT INTO "pmp_countries" VALUES(67,'ER','Eritrea');
INSERT INTO "pmp_countries" VALUES(68,'EE','Estonia');
INSERT INTO "pmp_countries" VALUES(69,'ET','Ethiopia');
INSERT INTO "pmp_countries" VALUES(70,'FK','Falkland Islands (Islas Malvinas)');
INSERT INTO "pmp_countries" VALUES(71,'FO','Faroe Islands');
INSERT INTO "pmp_countries" VALUES(72,'FJ','Fiji Islands');
INSERT INTO "pmp_countries" VALUES(73,'FI','Finland');
INSERT INTO "pmp_countries" VALUES(74,'FR','France');
INSERT INTO "pmp_countries" VALUES(75,'GF','French Guiana');
INSERT INTO "pmp_countries" VALUES(76,'PF','French Polynesia');
INSERT INTO "pmp_countries" VALUES(77,'TF','French Southern Territories');
INSERT INTO "pmp_countries" VALUES(78,'GA','Gabon');
INSERT INTO "pmp_countries" VALUES(79,'GM','Gambia, The');
INSERT INTO "pmp_countries" VALUES(80,'GE','Georgia');
INSERT INTO "pmp_countries" VALUES(81,'DE','Germany');
INSERT INTO "pmp_countries" VALUES(82,'GH','Ghana');
INSERT INTO "pmp_countries" VALUES(83,'GI','Gibraltar');
INSERT INTO "pmp_countries" VALUES(84,'GR','Greece');
INSERT INTO "pmp_countries" VALUES(85,'GL','Greenland');
INSERT INTO "pmp_countries" VALUES(86,'GD','Grenada');
INSERT INTO "pmp_countries" VALUES(87,'GP','Guadeloupe');
INSERT INTO "pmp_countries" VALUES(88,'GU','Guam');
INSERT INTO "pmp_countries" VALUES(89,'GT','Guatemala');
INSERT INTO "pmp_countries" VALUES(90,'GN','Guinea');
INSERT INTO "pmp_countries" VALUES(91,'GW','Guinea-Bissau');
INSERT INTO "pmp_countries" VALUES(92,'GY','Guyana');
INSERT INTO "pmp_countries" VALUES(93,'HT','Haiti');
INSERT INTO "pmp_countries" VALUES(94,'HM','Heard and McDonald Islands');
INSERT INTO "pmp_countries" VALUES(95,'HN','Honduras');
INSERT INTO "pmp_countries" VALUES(96,'HK','Hong Kong S.A.R.');
INSERT INTO "pmp_countries" VALUES(97,'HU','Hungary');
INSERT INTO "pmp_countries" VALUES(98,'IS','Iceland');
INSERT INTO "pmp_countries" VALUES(99,'IN','India');
INSERT INTO "pmp_countries" VALUES(100,'ID','Indonesia');
INSERT INTO "pmp_countries" VALUES(101,'IR','Iran');
INSERT INTO "pmp_countries" VALUES(102,'IQ','Iraq');
INSERT INTO "pmp_countries" VALUES(103,'IE','Ireland');
INSERT INTO "pmp_countries" VALUES(104,'IL','Israel');
INSERT INTO "pmp_countries" VALUES(105,'IT','Italy');
INSERT INTO "pmp_countries" VALUES(106,'JM','Jamaica');
INSERT INTO "pmp_countries" VALUES(107,'JP','Japan');
INSERT INTO "pmp_countries" VALUES(108,'JO','Jordan');
INSERT INTO "pmp_countries" VALUES(109,'KZ','Kazakhstan');
INSERT INTO "pmp_countries" VALUES(110,'KE','Kenya');
INSERT INTO "pmp_countries" VALUES(111,'KI','Kiribati');
INSERT INTO "pmp_countries" VALUES(112,'KR','Korea');
INSERT INTO "pmp_countries" VALUES(113,'KP','Korea, North');
INSERT INTO "pmp_countries" VALUES(114,'KW','Kuwait');
INSERT INTO "pmp_countries" VALUES(115,'KG','Kyrgyzstan');
INSERT INTO "pmp_countries" VALUES(116,'LA','Laos');
INSERT INTO "pmp_countries" VALUES(117,'LV','Latvia');
INSERT INTO "pmp_countries" VALUES(118,'LB','Lebanon');
INSERT INTO "pmp_countries" VALUES(119,'LS','Lesotho');
INSERT INTO "pmp_countries" VALUES(120,'LR','Liberia');
INSERT INTO "pmp_countries" VALUES(121,'LY','Libya');
INSERT INTO "pmp_countries" VALUES(122,'LI','Liechtenstein');
INSERT INTO "pmp_countries" VALUES(123,'LT','Lithuania');
INSERT INTO "pmp_countries" VALUES(124,'LU','Luxembourg');
INSERT INTO "pmp_countries" VALUES(125,'MO','Macau S.A.R.');
INSERT INTO "pmp_countries" VALUES(126,'MK','Macedonia, Former Yugoslav Republic of');
INSERT INTO "pmp_countries" VALUES(127,'MG','Madagascar');
INSERT INTO "pmp_countries" VALUES(128,'MW','Malawi');
INSERT INTO "pmp_countries" VALUES(129,'MY','Malaysia');
INSERT INTO "pmp_countries" VALUES(130,'MV','Maldives');
INSERT INTO "pmp_countries" VALUES(131,'ML','Mali');
INSERT INTO "pmp_countries" VALUES(132,'MT','Malta');
INSERT INTO "pmp_countries" VALUES(133,'MH','Marshall Islands');
INSERT INTO "pmp_countries" VALUES(134,'MQ','Martinique');
INSERT INTO "pmp_countries" VALUES(135,'MR','Mauritania');
INSERT INTO "pmp_countries" VALUES(136,'MU','Mauritius');
INSERT INTO "pmp_countries" VALUES(137,'YT','Mayotte');
INSERT INTO "pmp_countries" VALUES(138,'MX','Mexico');
INSERT INTO "pmp_countries" VALUES(139,'FM','Micronesia');
INSERT INTO "pmp_countries" VALUES(140,'MD','Moldova');
INSERT INTO "pmp_countries" VALUES(141,'MC','Monaco');
INSERT INTO "pmp_countries" VALUES(142,'MN','Mongolia');
INSERT INTO "pmp_countries" VALUES(143,'MS','Montserrat');
INSERT INTO "pmp_countries" VALUES(144,'MA','Morocco');
INSERT INTO "pmp_countries" VALUES(145,'MZ','Mozambique');
INSERT INTO "pmp_countries" VALUES(146,'MM','Myanmar');
INSERT INTO "pmp_countries" VALUES(147,'NA','Namibia');
INSERT INTO "pmp_countries" VALUES(148,'NR','Nauru');
INSERT INTO "pmp_countries" VALUES(149,'NP','Nepal');
INSERT INTO "pmp_countries" VALUES(150,'AN','Netherlands Antilles');
INSERT INTO "pmp_countries" VALUES(151,'NL','Netherlands, The');
INSERT INTO "pmp_countries" VALUES(152,'NC','New Caledonia');
INSERT INTO "pmp_countries" VALUES(153,'NZ','New Zealand');
INSERT INTO "pmp_countries" VALUES(154,'NI','Nicaragua');
INSERT INTO "pmp_countries" VALUES(155,'NE','Niger');
INSERT INTO "pmp_countries" VALUES(156,'NG','Nigeria');
INSERT INTO "pmp_countries" VALUES(157,'NU','Niue');
INSERT INTO "pmp_countries" VALUES(158,'NF','Norfolk Island');
INSERT INTO "pmp_countries" VALUES(159,'MP','Northern Mariana Islands');
INSERT INTO "pmp_countries" VALUES(160,'NO','Norway');
INSERT INTO "pmp_countries" VALUES(161,'OM','Oman');
INSERT INTO "pmp_countries" VALUES(162,'PK','Pakistan');
INSERT INTO "pmp_countries" VALUES(163,'PW','Palau');
INSERT INTO "pmp_countries" VALUES(164,'PA','Panama');
INSERT INTO "pmp_countries" VALUES(165,'PG','Papua new Guinea');
INSERT INTO "pmp_countries" VALUES(166,'PY','Paraguay');
INSERT INTO "pmp_countries" VALUES(167,'PE','Peru');
INSERT INTO "pmp_countries" VALUES(168,'PH','Philippines');
INSERT INTO "pmp_countries" VALUES(169,'PN','Pitcairn Island');
INSERT INTO "pmp_countries" VALUES(170,'PL','Poland');
INSERT INTO "pmp_countries" VALUES(171,'PT','Portugal');
INSERT INTO "pmp_countries" VALUES(172,'PR','Puerto Rico');
INSERT INTO "pmp_countries" VALUES(173,'QA','Qatar');
INSERT INTO "pmp_countries" VALUES(174,'RE','Reunion');
INSERT INTO "pmp_countries" VALUES(175,'RO','Romania');
INSERT INTO "pmp_countries" VALUES(176,'RU','Russia');
INSERT INTO "pmp_countries" VALUES(177,'RW','Rwanda');
INSERT INTO "pmp_countries" VALUES(178,'SH','Saint Helena');
INSERT INTO "pmp_countries" VALUES(179,'KN','Saint Kitts And Nevis');
INSERT INTO "pmp_countries" VALUES(180,'LC','Saint Lucia');
INSERT INTO "pmp_countries" VALUES(181,'PM','Saint Pierre and Miquelon');
INSERT INTO "pmp_countries" VALUES(182,'VC','Saint Vincent And The Grenadines');
INSERT INTO "pmp_countries" VALUES(183,'WS','Samoa');
INSERT INTO "pmp_countries" VALUES(184,'SM','San Marino');
INSERT INTO "pmp_countries" VALUES(185,'ST','Sao Tome and Principe');
INSERT INTO "pmp_countries" VALUES(186,'SA','Saudi Arabia');
INSERT INTO "pmp_countries" VALUES(187,'SN','Senegal');
INSERT INTO "pmp_countries" VALUES(188,'SC','Seychelles');
INSERT INTO "pmp_countries" VALUES(189,'SL','Sierra Leone');
INSERT INTO "pmp_countries" VALUES(190,'SG','Singapore, Republic of');
INSERT INTO "pmp_countries" VALUES(191,'SK','Slovakia');
INSERT INTO "pmp_countries" VALUES(192,'SI','Slovenia');
INSERT INTO "pmp_countries" VALUES(193,'SB','Solomon Islands');
INSERT INTO "pmp_countries" VALUES(194,'SO','Somalia');
INSERT INTO "pmp_countries" VALUES(195,'ZA','South Africa');
INSERT INTO "pmp_countries" VALUES(196,'GS','South Georgia And The South Sandwich Islands');
INSERT INTO "pmp_countries" VALUES(197,'ES','Spain');
INSERT INTO "pmp_countries" VALUES(198,'LK','Sri Lanka');
INSERT INTO "pmp_countries" VALUES(199,'SD','Sudan');
INSERT INTO "pmp_countries" VALUES(200,'SR','Suriname');
INSERT INTO "pmp_countries" VALUES(201,'SJ','Svalbard And Jan Mayen Islands');
INSERT INTO "pmp_countries" VALUES(202,'SZ','Swaziland');
INSERT INTO "pmp_countries" VALUES(203,'SE','Sweden');
INSERT INTO "pmp_countries" VALUES(204,'CH','Switzerland');
INSERT INTO "pmp_countries" VALUES(205,'SY','Syria');
INSERT INTO "pmp_countries" VALUES(206,'TW','Taiwan');
INSERT INTO "pmp_countries" VALUES(207,'TJ','Tajikistan');
INSERT INTO "pmp_countries" VALUES(208,'TZ','Tanzania');
INSERT INTO "pmp_countries" VALUES(209,'TH','Thailand');
INSERT INTO "pmp_countries" VALUES(210,'TG','Togo');
INSERT INTO "pmp_countries" VALUES(211,'TK','Tokelau');
INSERT INTO "pmp_countries" VALUES(212,'TO','Tonga');
INSERT INTO "pmp_countries" VALUES(213,'TT','Trinidad And Tobago');
INSERT INTO "pmp_countries" VALUES(214,'TN','Tunisia');
INSERT INTO "pmp_countries" VALUES(215,'TR','Turkey');
INSERT INTO "pmp_countries" VALUES(216,'TM','Turkmenistan');
INSERT INTO "pmp_countries" VALUES(217,'TC','Turks And Caicos Islands');
INSERT INTO "pmp_countries" VALUES(218,'TV','Tuvalu');
INSERT INTO "pmp_countries" VALUES(219,'UG','Uganda');
INSERT INTO "pmp_countries" VALUES(220,'UA','Ukraine');
INSERT INTO "pmp_countries" VALUES(221,'AE','United Arab Emirates');
INSERT INTO "pmp_countries" VALUES(222,'UK','United Kingdom');
INSERT INTO "pmp_countries" VALUES(223,'US','United States');
INSERT INTO "pmp_countries" VALUES(224,'UM','United States Minor Outlying Islands');
INSERT INTO "pmp_countries" VALUES(225,'UY','Uruguay');
INSERT INTO "pmp_countries" VALUES(226,'UZ','Uzbekistan');
INSERT INTO "pmp_countries" VALUES(227,'VU','Vanuatu');
INSERT INTO "pmp_countries" VALUES(228,'VA','Vatican City State (Holy See)');
INSERT INTO "pmp_countries" VALUES(229,'VE','Venezuela');
INSERT INTO "pmp_countries" VALUES(230,'VN','Vietnam');
INSERT INTO "pmp_countries" VALUES(231,'VG','Virgin Islands (British)');
INSERT INTO "pmp_countries" VALUES(232,'VI','Virgin Islands (US)');
INSERT INTO "pmp_countries" VALUES(233,'WF','Wallis And Futuna Islands');
INSERT INTO "pmp_countries" VALUES(234,'YE','Yemen');
INSERT INTO "pmp_countries" VALUES(235,'YU','Yugoslavia');
INSERT INTO "pmp_countries" VALUES(236,'ZM','Zambia');
INSERT INTO "pmp_countries" VALUES(237,'ZW','Zimbabwe');
CREATE TABLE [pmp_addresstypes] (
[atpAddressTypeID] INTEGER  NOT NULL PRIMARY KEY AUTOINCREMENT,
[atpAddressType] TEXT  NULL,
[atpLanguageID] INTEGER  NULL
);
INSERT INTO "pmp_addresstypes" VALUES(1,'Mailing',1);
INSERT INTO "pmp_addresstypes" VALUES(2,'Residential',1);
INSERT INTO "pmp_addresstypes" VALUES(3,'Business',1);
INSERT INTO "pmp_addresstypes" VALUES(4,'Permanent',1);
CREATE TABLE SQLITEADMIN_QUERIES(ID INTEGER PRIMARY KEY,NAME VARCHAR(100),SQL TEXT);
CREATE TABLE [pmp_contacts] (
[ctnContactID] INTEGER  PRIMARY KEY AUTOINCREMENT NOT NULL,
[ctnPersonID] INTEGER  NULL,
[ctnContactTypeID] INTEGER  NULL,
[ctnContact] TEXT  NULL
);
INSERT INTO "pmp_contacts" VALUES(1,1,14,'orangepyrite');
INSERT INTO "pmp_contacts" VALUES(2,1,5,'Pyrite21');
INSERT INTO "pmp_contacts" VALUES(3,1,11,'http://pysquared.com/');
INSERT INTO "pmp_contacts" VALUES(4,2,14,'lord.izuriel');
CREATE TABLE [pmp_categories] (
[catCategoryID] INTEGER  NOT NULL PRIMARY KEY AUTOINCREMENT,
[catCategoryName] TEXT  NULL
);
INSERT INTO "pmp_categories" VALUES(1,'Family');
INSERT INTO "pmp_categories" VALUES(2,'Friends');
CREATE TABLE [pmp_categorylink] (
[clkCategoryLinkID] INTEGER  NOT NULL PRIMARY KEY AUTOINCREMENT,
[clkCategoryID] INTEGER  NULL,
[clkPersonID] INTEGER  NULL
);
INSERT INTO "pmp_categorylink" VALUES(1,2,1);
INSERT INTO "pmp_categorylink" VALUES(2,2,2);
CREATE TABLE pmp_people (psnPersonID INTEGER PRIMARY KEY AUTOINCREMENT, psnPrefix TEXT, psnSuffix TEXT, psnFirstName TEXT, psnMiddleName TEXT, psnLastName TEXT, psnMaidenName TEXT, psnGender INTEGER, psnEyeColor TEXT, psnHairColor TEXT, psnHeight TEXT, psnWeight TEXT, psnBirthday VARCHAR(10), psnDescription TEXT, psnNickName TEXT, psnDemonymID INTEGER, psnPhotoBinary BLOB, psnPhotoFileName VARCHAR(100), psnLastUpdate VARCHAR(10), psnOccupation TEXT);
INSERT INTO "pmp_people" VALUES(1,'','','Brandon','',' Tanner','Unknown','Male','Green','Brown','6''2','225 lbs','1979-12-12','Hoi Polloi Author','Pyrite','Unknown','','1.jpg','2007-12-23','Student');
INSERT INTO "pmp_people" VALUES(2,'','','Brandon','','Buck','','','','','','','0000-00-00','Hoi Polloi Author','','','','2.jpg','2007-12-23','Student');
CREATE TABLE pmp_addresses (adrAddressID INTEGER PRIMARY KEY AUTOINCREMENT, adrAddressTypeID INTEGER, adrPersonID INTEGER, adrAddressLabel TEXT, adrAddressLine1 TEXT, adrAddressLine2 TEXT, adrAddressLine3 TEXT, adrCity TEXT, adrState TEXT, adrZip TEXT, adrCountryID INTEGER, adrDistrict TEXT);
CREATE TABLE pmp_demonyms(demID INTEGER PRIMARY KEY, demDemonym VARCHAR(25));
INSERT INTO "pmp_demonyms" VALUES(1,'Afghan');
INSERT INTO "pmp_demonyms" VALUES(2,'Albanian');
INSERT INTO "pmp_demonyms" VALUES(3,'Algerian');
INSERT INTO "pmp_demonyms" VALUES(4,'Andorran');
INSERT INTO "pmp_demonyms" VALUES(5,'Angolan');
INSERT INTO "pmp_demonyms" VALUES(6,'Antiguan');
INSERT INTO "pmp_demonyms" VALUES(7,'Argentinean');
INSERT INTO "pmp_demonyms" VALUES(8,'Armenian');
INSERT INTO "pmp_demonyms" VALUES(9,'Australian');
INSERT INTO "pmp_demonyms" VALUES(10,'Austrian');
INSERT INTO "pmp_demonyms" VALUES(11,'Azerbaijani');
INSERT INTO "pmp_demonyms" VALUES(12,'Bahamian');
INSERT INTO "pmp_demonyms" VALUES(13,'Bahraini');
INSERT INTO "pmp_demonyms" VALUES(14,'Bangladeshi');
INSERT INTO "pmp_demonyms" VALUES(15,'Barbadian');
INSERT INTO "pmp_demonyms" VALUES(16,'Belarusian');
INSERT INTO "pmp_demonyms" VALUES(17,'Belgian');
INSERT INTO "pmp_demonyms" VALUES(18,'Belizean');
INSERT INTO "pmp_demonyms" VALUES(19,'Beninese');
INSERT INTO "pmp_demonyms" VALUES(20,'Bhutanese');
INSERT INTO "pmp_demonyms" VALUES(21,'Bolivian');
INSERT INTO "pmp_demonyms" VALUES(22,'Bosnian');
INSERT INTO "pmp_demonyms" VALUES(23,'Motswana');
INSERT INTO "pmp_demonyms" VALUES(24,'Brazilian');
INSERT INTO "pmp_demonyms" VALUES(25,'Bruneian');
INSERT INTO "pmp_demonyms" VALUES(26,'Bulgarian');
INSERT INTO "pmp_demonyms" VALUES(27,'Burkinabe');
INSERT INTO "pmp_demonyms" VALUES(28,'Burundian');
INSERT INTO "pmp_demonyms" VALUES(29,'Cambodian');
INSERT INTO "pmp_demonyms" VALUES(30,'Cameroonian');
INSERT INTO "pmp_demonyms" VALUES(31,'Canadian');
INSERT INTO "pmp_demonyms" VALUES(32,'Cape Verdian');
INSERT INTO "pmp_demonyms" VALUES(33,'Central African');
INSERT INTO "pmp_demonyms" VALUES(34,'Chadian');
INSERT INTO "pmp_demonyms" VALUES(35,'Chilean');
INSERT INTO "pmp_demonyms" VALUES(36,'Chinese');
INSERT INTO "pmp_demonyms" VALUES(37,'Colombian');
INSERT INTO "pmp_demonyms" VALUES(38,'Comoran');
INSERT INTO "pmp_demonyms" VALUES(39,'Congolese');
INSERT INTO "pmp_demonyms" VALUES(40,'Congolese');
INSERT INTO "pmp_demonyms" VALUES(41,'Costa Rican');
INSERT INTO "pmp_demonyms" VALUES(42,'Ivorian');
INSERT INTO "pmp_demonyms" VALUES(43,'Croatian');
INSERT INTO "pmp_demonyms" VALUES(44,'Cuban');
INSERT INTO "pmp_demonyms" VALUES(45,'Cypriot');
INSERT INTO "pmp_demonyms" VALUES(46,'Czech');
INSERT INTO "pmp_demonyms" VALUES(47,'Danish');
INSERT INTO "pmp_demonyms" VALUES(48,'Djibouti');
INSERT INTO "pmp_demonyms" VALUES(49,'Dominican');
INSERT INTO "pmp_demonyms" VALUES(50,'Dominican');
INSERT INTO "pmp_demonyms" VALUES(51,'East Timorese');
INSERT INTO "pmp_demonyms" VALUES(52,'Ecuadorean');
INSERT INTO "pmp_demonyms" VALUES(53,'Egyptian');
INSERT INTO "pmp_demonyms" VALUES(54,'Salvadoran');
INSERT INTO "pmp_demonyms" VALUES(55,'Equatorial Guinean');
INSERT INTO "pmp_demonyms" VALUES(56,'Eritrean');
INSERT INTO "pmp_demonyms" VALUES(57,'Estonian');
INSERT INTO "pmp_demonyms" VALUES(58,'Ethiopian');
INSERT INTO "pmp_demonyms" VALUES(59,'Fijian');
INSERT INTO "pmp_demonyms" VALUES(60,'Finnish');
INSERT INTO "pmp_demonyms" VALUES(61,'French');
INSERT INTO "pmp_demonyms" VALUES(62,'Gabonese');
INSERT INTO "pmp_demonyms" VALUES(63,'Gambian');
INSERT INTO "pmp_demonyms" VALUES(64,'Georgian');
INSERT INTO "pmp_demonyms" VALUES(65,'German');
INSERT INTO "pmp_demonyms" VALUES(66,'Ghanaian');
INSERT INTO "pmp_demonyms" VALUES(67,'Greek');
INSERT INTO "pmp_demonyms" VALUES(68,'Grenadian');
INSERT INTO "pmp_demonyms" VALUES(69,'Guatemalan');
INSERT INTO "pmp_demonyms" VALUES(70,'Guinean');
INSERT INTO "pmp_demonyms" VALUES(71,'Guinea-Bissauan');
INSERT INTO "pmp_demonyms" VALUES(72,'Guyanese');
INSERT INTO "pmp_demonyms" VALUES(73,'Haitian');
INSERT INTO "pmp_demonyms" VALUES(74,'Honduran');
INSERT INTO "pmp_demonyms" VALUES(75,'Hungarian');
INSERT INTO "pmp_demonyms" VALUES(76,'Icelander');
INSERT INTO "pmp_demonyms" VALUES(77,'Indian');
INSERT INTO "pmp_demonyms" VALUES(78,'Indonesian');
INSERT INTO "pmp_demonyms" VALUES(79,'Iranian');
INSERT INTO "pmp_demonyms" VALUES(80,'Iraqi');
INSERT INTO "pmp_demonyms" VALUES(81,'Irish');
INSERT INTO "pmp_demonyms" VALUES(82,'Israeli');
INSERT INTO "pmp_demonyms" VALUES(83,'Italian');
INSERT INTO "pmp_demonyms" VALUES(84,'Jamaican');
INSERT INTO "pmp_demonyms" VALUES(85,'Japanese');
INSERT INTO "pmp_demonyms" VALUES(86,'Jordanian');
INSERT INTO "pmp_demonyms" VALUES(87,'Kazakhstani');
INSERT INTO "pmp_demonyms" VALUES(88,'Kenyan');
INSERT INTO "pmp_demonyms" VALUES(89,'I-Kiribati');
INSERT INTO "pmp_demonyms" VALUES(90,'North Korean');
INSERT INTO "pmp_demonyms" VALUES(91,'South Korean');
INSERT INTO "pmp_demonyms" VALUES(92,'Kuwaiti');
INSERT INTO "pmp_demonyms" VALUES(93,'Kirghiz');
INSERT INTO "pmp_demonyms" VALUES(94,'Laotian');
INSERT INTO "pmp_demonyms" VALUES(95,'Latvian');
INSERT INTO "pmp_demonyms" VALUES(96,'Lebanese');
INSERT INTO "pmp_demonyms" VALUES(97,'Mosotho');
INSERT INTO "pmp_demonyms" VALUES(98,'Liberian');
INSERT INTO "pmp_demonyms" VALUES(99,'Libyan');
INSERT INTO "pmp_demonyms" VALUES(100,'Liechtensteiner');
INSERT INTO "pmp_demonyms" VALUES(101,'Lithuanian');
INSERT INTO "pmp_demonyms" VALUES(102,'Luxembourger');
INSERT INTO "pmp_demonyms" VALUES(103,'Macedonian');
INSERT INTO "pmp_demonyms" VALUES(104,'Malagasy');
INSERT INTO "pmp_demonyms" VALUES(105,'Malawian');
INSERT INTO "pmp_demonyms" VALUES(106,'Malaysian');
INSERT INTO "pmp_demonyms" VALUES(107,'Maldivan');
INSERT INTO "pmp_demonyms" VALUES(108,'Malian');
INSERT INTO "pmp_demonyms" VALUES(109,'Maltese');
INSERT INTO "pmp_demonyms" VALUES(110,'Marshallese');
INSERT INTO "pmp_demonyms" VALUES(111,'Mauritanian');
INSERT INTO "pmp_demonyms" VALUES(112,'Mauritian');
INSERT INTO "pmp_demonyms" VALUES(113,'Mexican');
INSERT INTO "pmp_demonyms" VALUES(114,'Micronesian');
INSERT INTO "pmp_demonyms" VALUES(115,'Moldovan');
INSERT INTO "pmp_demonyms" VALUES(116,'Monegasque');
INSERT INTO "pmp_demonyms" VALUES(117,'Mongolian');
INSERT INTO "pmp_demonyms" VALUES(118,'Moroccan');
INSERT INTO "pmp_demonyms" VALUES(119,'Mozambican');
INSERT INTO "pmp_demonyms" VALUES(120,'Burmese');
INSERT INTO "pmp_demonyms" VALUES(121,'Namibian');
INSERT INTO "pmp_demonyms" VALUES(122,'Nauruan');
INSERT INTO "pmp_demonyms" VALUES(123,'Nepalese');
INSERT INTO "pmp_demonyms" VALUES(124,'Dutch');
INSERT INTO "pmp_demonyms" VALUES(125,'New Zealander');
INSERT INTO "pmp_demonyms" VALUES(126,'Nicaraguan');
INSERT INTO "pmp_demonyms" VALUES(127,'Nigerien');
INSERT INTO "pmp_demonyms" VALUES(128,'Nigerian');
INSERT INTO "pmp_demonyms" VALUES(129,'Norwegian');
INSERT INTO "pmp_demonyms" VALUES(130,'Omani');
INSERT INTO "pmp_demonyms" VALUES(131,'Pakistani');
INSERT INTO "pmp_demonyms" VALUES(132,'Palauan');
INSERT INTO "pmp_demonyms" VALUES(133,'Panamanian');
INSERT INTO "pmp_demonyms" VALUES(134,'Papua New Guinean');
INSERT INTO "pmp_demonyms" VALUES(135,'Paraguayan');
INSERT INTO "pmp_demonyms" VALUES(136,'Peruvian');
INSERT INTO "pmp_demonyms" VALUES(137,'Filipino');
INSERT INTO "pmp_demonyms" VALUES(138,'Polish');
INSERT INTO "pmp_demonyms" VALUES(139,'Portuguese');
INSERT INTO "pmp_demonyms" VALUES(140,'Qatari');
INSERT INTO "pmp_demonyms" VALUES(141,'Romanian');
INSERT INTO "pmp_demonyms" VALUES(142,'Russian');
INSERT INTO "pmp_demonyms" VALUES(143,'Rwandan');
INSERT INTO "pmp_demonyms" VALUES(144,'Kittian');
INSERT INTO "pmp_demonyms" VALUES(145,'Saint Lucian');
INSERT INTO "pmp_demonyms" VALUES(146,'Samoan');
INSERT INTO "pmp_demonyms" VALUES(147,'Sammarinese');
INSERT INTO "pmp_demonyms" VALUES(148,'Sao Tomean');
INSERT INTO "pmp_demonyms" VALUES(149,'Saudi Arabian');
INSERT INTO "pmp_demonyms" VALUES(150,'Senegalese');
INSERT INTO "pmp_demonyms" VALUES(151,'Serbian');
INSERT INTO "pmp_demonyms" VALUES(152,'Seychellois');
INSERT INTO "pmp_demonyms" VALUES(153,'Sierra Leonean');
INSERT INTO "pmp_demonyms" VALUES(154,'Singaporean');
INSERT INTO "pmp_demonyms" VALUES(155,'Slovak');
INSERT INTO "pmp_demonyms" VALUES(156,'Slovene');
INSERT INTO "pmp_demonyms" VALUES(157,'Solomon Islander');
INSERT INTO "pmp_demonyms" VALUES(158,'Somali');
INSERT INTO "pmp_demonyms" VALUES(159,'South African');
INSERT INTO "pmp_demonyms" VALUES(160,'Spanish');
INSERT INTO "pmp_demonyms" VALUES(161,'Sri Lankan');
INSERT INTO "pmp_demonyms" VALUES(162,'Sudanese');
INSERT INTO "pmp_demonyms" VALUES(163,'Surinamer');
INSERT INTO "pmp_demonyms" VALUES(164,'Swazi');
INSERT INTO "pmp_demonyms" VALUES(165,'Swedish');
INSERT INTO "pmp_demonyms" VALUES(166,'Swiss');
INSERT INTO "pmp_demonyms" VALUES(167,'Syrian');
INSERT INTO "pmp_demonyms" VALUES(168,'Taiwanese');
INSERT INTO "pmp_demonyms" VALUES(169,'Tadzhik');
INSERT INTO "pmp_demonyms" VALUES(170,'Tanzanian');
INSERT INTO "pmp_demonyms" VALUES(171,'Thai');
INSERT INTO "pmp_demonyms" VALUES(172,'Togolese');
INSERT INTO "pmp_demonyms" VALUES(173,'Tongan');
INSERT INTO "pmp_demonyms" VALUES(174,'Trinidadian');
INSERT INTO "pmp_demonyms" VALUES(175,'Tunisian');
INSERT INTO "pmp_demonyms" VALUES(176,'Turkish');
INSERT INTO "pmp_demonyms" VALUES(177,'Turkmen');
INSERT INTO "pmp_demonyms" VALUES(178,'Tuvaluan');
INSERT INTO "pmp_demonyms" VALUES(179,'Ugandan');
INSERT INTO "pmp_demonyms" VALUES(180,'Ukrainian');
INSERT INTO "pmp_demonyms" VALUES(181,'Emirian');
INSERT INTO "pmp_demonyms" VALUES(182,'British');
INSERT INTO "pmp_demonyms" VALUES(183,'American');
INSERT INTO "pmp_demonyms" VALUES(184,'Uruguayan');
INSERT INTO "pmp_demonyms" VALUES(185,'Uzbekistani');
INSERT INTO "pmp_demonyms" VALUES(186,'Ni-Vanuatu');
INSERT INTO "pmp_demonyms" VALUES(187,'Texian');
INSERT INTO "pmp_demonyms" VALUES(188,'Venezuelan');
INSERT INTO "pmp_demonyms" VALUES(189,'Vietnamese');
INSERT INTO "pmp_demonyms" VALUES(190,'Yemeni');
INSERT INTO "pmp_demonyms" VALUES(191,'Zambian');
INSERT INTO "pmp_demonyms" VALUES(192,'Zimbabwean');
INSERT INTO "pmp_demonyms" VALUES(193,'Unknown');
COMMIT;
